#!/usr/bin/env python3
import logging
import pdb
import sys

from redbaron import RedBaron

from gitmergepy.applyier import apply_changes
from gitmergepy.differ import compute_diff_iterables


def parse_file(filename):
    with open(filename, 'r') as f:
        return RedBaron(f.read())


def main():
    logging.basicConfig(level=logging.DEBUG, format='%(message)s')
    logging.debug(" ".join(sys.argv))
    base_file = sys.argv[1]
    other_file = sys.argv[2]
    current_file = sys.argv[3]

    try:
        r = merge_files(base_file, current_file, other_file)
    except Exception as e:
        pdb.post_mortem(e.__traceback__)
    else:
        sys.exit(0 if r else 1)


def merge_files(base_file, current_file, other_file):
    base_ast = parse_file(base_file)
    current_ast = parse_file(current_file)
    other_ast = parse_file(other_file)
    merge_ast(base_ast, current_ast, other_ast)
    output = other_ast.dumps()
    with open(other_file, 'w') as out:
        out.write(output)
    return ">>>>>>>>>>>>>>>>>>>" not in output


def merge_ast(base_ast, current_ast, other_ast):
    changes = compute_diff_iterables(base_ast, current_ast)
    # logging.info("Changes %r", changes)
    apply_changes(other_ast, changes)


if __name__ == '__main__':
    main()
